### ISSUE TITLE
turbolinks-related stuff resurrects in code example in blog

### ISSUE THREAD

**Issue by fwolfst** [iridakos/rails-chat-tutorial#1]
In the blog post https://iridakos.com/tutorials/2019/04/04/creating-chat-application-rails-websockets.html
the code example after
`We have to add this partial in the application layout. Edit app/views/layouts/application.html.erb and change its contents to:` contains `turbolinks` stuff which should have been removed if one follows the previous steps.

**Comment by iridakos** [comment]
Hi @fwolfst ,

Thank you very much for pointing out, just fixed! :+1:
