### ISSUE TITLE
Clear cache at end?  Ran into a User error with Warden

### ISSUE THREAD

**Issue by tonydehnke** [iridakos/rails-chat-tutorial#10]
When I finished up the last bit and tried to reload my webpage, I would get an error:

`  
config/initializers/warden_hooks.rb:1:in `block in <main>'
Started GET "/" for ::1 at 2019-04-13 15:17:35 -0700
Processing by RoomsController#index as HTML
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ /Users/tdehnke/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/log_subscriber.rb:98
Completed 500 Internal Server Error in 27ms (ActiveRecord: 1.0ms)

  
NameError (undefined local variable or method `user' for main:Object
Did you mean?  super):
  
config/initializers/warden_hooks.rb:1:in `block in <main>'
`

I couldn't find anything and eventually decided to see if it was a cache error or something.  So I ran the `rails tmp:cache:clear` command again (after shutting down the server) and then things worked.  So not sure if it was my system or what... but if others run into it, maybe add that command at the end again.

**Comment by iridakos** [comment]
Hi @tonydehnke , I think somewhere between the steps the server has to be restarted. I will follow the steps one by one again and update the post with prompts to restart the server as needed.

Thank you for all of your reports!
