### ISSUE TITLE
application.js - requires order

### ISSUE THREAD

**Issue by mdanlowski** [iridakos/rails-chat-tutorial#11]
HI! 
A really cool tutorial :) One of the most bulletproof I've followed so far.
Dunno if it was already pointed out - apologies if so - but 
`//=require jquery3` and all the stuff
must come before 
`//=require_tree`. Otherwise js throws $ not defined in the browser.
The article says `append the following...` and does not mention the order :) 
just a cosmetic, though it might stave off some beginners

Cheers!

**Comment by iridakos** [comment]
Hi @mdanlowski and thank you very much for the feedback :)

You are right, the order of requirements in
[application.js](https://github.com/iridakos/rails-chat-tutorial/blob/master/app/assets/javascripts/application.js) was not mentioned in the post. Post updated.

https://iridakos.com/tutorials/2019/04/04/creating-chat-application-rails-websockets.html#acknowledgments
