### ISSUE TITLE
Not show name of account in chat room 

### ISSUE THREAD

**Issue by tuandnacv** [iridakos/rails-chat-tutorial#12]
Hi @iridakos,
Why are not you add name of user in room. Have another way in Streams for show multi informations that you want to show them. You can read [here](https://edgeguides.rubyonrails.org/action_cable_overview.html#streams)

**Comment by iridakos** [comment]
Hi @tuandnacv 
The name was left out for simplicity (I chose to just display the avatar). I might update it in the future to include the name as well :+1:
