### ISSUE TITLE
syntax error in dockerfile

### ISSUE THREAD

**Issue by abhinaykumar** [iridakos/rails-chat-tutorial#13]
At the first step where we add ruby version to be complied in Dockerfile (`FROM ruby-2.6.2:stretch`) throws an error:
```
Sending build context to Docker daemon  249.7MB
Step 1/1 : FROM ruby-2.6.2:stretch
pull access denied for ruby-2.6.2, repository does not exist or may require 'docker login'
```
It should be `FROM ruby:2.6.2-stretch`.

**Comment by iridakos** [comment]
@abhinaykumar Thank you very match for pointing it out. I just fixed that on the post.
