### ISSUE TITLE
before_action :authenticate_user! mentioned twice

### ISSUE THREAD

**Issue by Kawsay** [iridakos/rails-chat-tutorial#15]
Hey,

first of all big thanks for your guides and your blog, as a beginner I'm finding super interesting content !

Just a little detail concerning your guide about building a chat using Rails & WebSockets: in the firsts steps you're asking us to add `before_action :authenticate_user! ` twice. Really minor "issue" :)

I'm back to your guide, have a great day !

**Comment by iridakos** [comment]
Hi @Kawsay and merci beaucoup pour vos commentaires! (I'm learning French, in case it's wrong I meant "Thank you very much for your feedback" :D )

I just updated the blog, [voilà](https://iridakos.com/tutorials/2019/04/04/creating-chat-application-rails-websockets.html#acknowledgments)

Thank you very much for pointing this out :+1:

**Comment by Kawsay** [comment]
Héhé c'est parfait ! N'hésite pas à me solliciter si tu veux échanger en français :) ! (I've to finish my chat application before chatting tho :p)

**Comment by iridakos** [comment]
Héhé merci beaucoup !
