### ISSUE TITLE
Messages are not coming dynamically

### ISSUE THREAD

**Issue by SurajDbhat** [iridakos/rails-chat-tutorial#16]
as you type message and send message it is not auto loading..we have to refresh then only it is getting displayed.

**Comment by djany082** [comment]
Having the same problem, No messages are showing on the console

**Comment by djany082** [comment]
Maybe this will help 
![Screenshot 2019-10-15 at 14 34 40](https://user-images.githubusercontent.com/19593976/66831896-0403da80-ef59-11e9-87b7-469c9143347a.png)

**Comment by djany082** [comment]
![Screenshot 2019-10-15 at 15 09 43](https://user-images.githubusercontent.com/19593976/66834427-dcfbd780-ef5d-11e9-9653-229c2f5f8fda.png)


Other variables are defined but i'm failing to understand where the App is imported or defined

**Comment by djany082** [comment]
[Screen Recording 2019-10-15 at 15.58.34.zip](https://github.com/iridakos/rails-chat-tutorial/files/3729697/Screen.Recording.2019-10-15.at.15.58.34.zip)
please check the zipped video. It is now not giving me that error, Only problem its not sending as real time. always need to refresh

**Comment by djany082** [comment]
Okay I am having this issue only now: Uncaught ReferenceError: App is not defined 

it is showing on the console log

**Comment by Yardboy** [comment]
See [my comment](https://github.com/iridakos/rails-chat-tutorial/issues/25#issuecomment-618474033) on issue #25

**Comment by iridakos** [comment]
I am closing the issue. Feel free to re-open it if you still have the described problem.

@Yardboy Thank you for answering!
