### ISSUE TITLE
Application won't start in production mode

### ISSUE THREAD

**Issue by llabake** [iridakos/rails-chat-tutorial#18]
After creating the Redis and Postgres container, creating the application container with the command below was unsuccessful
```
docker run --name rails-chat-tutorial-web \
            -e DATABASE_HOST=172.17.0.1 \
            -e DATABASE_PORT=5432 \
            -e DATABASE_USERNAME=postgres \
            -e DATABASE_PASSWORD=password \
            -e REDIS_URL=redis://172.17.0.1:6379/1 \
            -p 3000:3000 \
            rails-chat-tutorial
```
I was getting *Switch to inspect mode*

<img width="1440" alt="Screenshot 2019-10-01 at 5 35 07 PM" src="https://user-images.githubusercontent.com/29184825/65983379-42879880-e475-11e9-900a-426ccc1ae183.png">
<img width="796" alt="Screenshot 2019-10-01 at 5 35 49 PM" src="https://user-images.githubusercontent.com/29184825/65983455-6f3bb000-e475-11e9-9e31-e677bea29423.png">

<img width="1440" alt="Screenshot 2019-10-01 at 5 35 59 PM" src="https://user-images.githubusercontent.com/29184825/65983496-82e71680-e475-11e9-8177-821c2d839048.png">

**Comment by Yardboy** [comment]
The first part of the REDIS_URL should be the host:

`REDIS_URL=host://redis:6379/1`

So, try:

`REDIS_URL=172.17.0.1://redis:6379/1`

Also, if your redis container is set up and linked correctly, you can avoid the IP address altogether and just do:

`REDIS_URL: redis://redis:6379/1`

**Comment by iridakos** [comment]
@llabake Hi, I am closing the issue. If you still have the problem feel free to re-open it.

Thank you!
