### ISSUE TITLE
message owner

### ISSUE THREAD

**Issue by Austin25309w** [iridakos/rails-chat-tutorial#19]
when user creates a message it only see the user's image. How do I add user's name next to the user? Thanks!

**Comment by Yardboy** [comment]
I think you may have missed in the instructions where he moved the gravatar url method from the `ApplicationHelper` to the `User` model.

**Comment by iridakos** [comment]
I am closing the issue but if the problem persists after following @Yardboy's suggestion, feel free to re-open it.

Thank you for reporting!
