### ISSUE TITLE
Devise Setup typo

### ISSUE THREAD

**Issue by maria-kravtsova** [iridakos/rails-chat-tutorial#2]
Here:
<img width="958" alt="Screen Shot 2019-04-07 at 3 48 54 PM" src="https://user-images.githubusercontent.com/7818735/55688950-b6c10380-594c-11e9-8cfa-cb6b19658999.png">

I believe it creates the table `users` so this line:

`add_index :user,  :username,             unique: true` 
should be:

`add_index :users,  :username,             unique: true`

At least it worked for me. 

Thank you for writing the tutorial, it's very helpful so far.

**Comment by iridakos** [comment]
Hi @maria-kravtsova,

You are absolutely right, I just fixed that.

Thank you very much for pointing it out!
