### ISSUE TITLE
Message only displays after refresh

### ISSUE THREAD

**Issue by robb52** [iridakos/rails-chat-tutorial#27]
I was following along and everything was working as expected until after the updated show.html.erb. The console shows a message is being created:
<img width="979" alt="Screen Shot 2019-12-03 at 5 44 59 PM" src="https://user-images.githubusercontent.com/32523334/70105025-a43ebd00-15f4-11ea-856f-ae2e12cf7f86.png">

But page needs to refresh before it shows in browser. Any help or suggestion would be great!!
My code: https://github.com/robb52/rails-chatroom

Thanks!

**Comment by Bharanidharan7708** [comment]
I too have the same issue

**Comment by Yardboy** [comment]
You are missing the broadcast line in `room_messages_controller#create`:

`RoomChannel.broadcast_to @room, @room_message`

**Comment by iridakos** [comment]
Thank you for answering @Yardboy :rocket:
