### ISSUE TITLE
Load messages with `includes(:user)`  in RoomsController#show to avoid N+1

### ISSUE THREAD

**Issue by antico5** [iridakos/rails-chat-tutorial#3]
Thanks for the tutorial, it's well explained and comprehensive. One detail I would like to point out is that when you want to include the user's gravatar url in RoomMessage#as_json, you will have a N+1 query problem on your RoomsController#show action. I think it would be nice to point this out and add something like `@room_messages = @room.room_messages.includes(:user)` to your show action, and explain the reason for this. N+1 are a very expensive mistake in the long run and is very frequent among junior developers. You can never remind them too much about them!

**Comment by iridakos** [comment]
You are absolutely right, thanks for pointing out!

I will keep this issue open until I update the article. :+1:

**Comment by iridakos** [comment]
Done.

https://iridakos.com/tutorials/2019/04/04/creating-chat-application-rails-websockets.html#acknowledgments
