### ISSUE TITLE
Message need a refresh and No template found for RoomMessagesController#create, rendering head :no_content

### ISSUE THREAD

**Issue by Goku-San** [iridakos/rails-chat-tutorial#37]
Hello nice tutorial, read it few days ago and decided to do it. 

So I don't know how to solve these two problems 
1. Messages need a refresh to start the stream and 
2. No template found for RoomMessagesController#create, rendering head :no_content error.

The second one is same as [#17](https://github.com/iridakos/rails-chat-tutorial/issues/17)

So any help is appreciated.

**Comment by AndresGarciadelaHuerta** [comment]
Hi!

I managed to fix the first problem by adding `$(document).on('turbolinks:load',` before all the javascript functions. For example:

```javascript
$(document).on('turbolinks:load', function() {
       // code here
});
```

This will wait for the `data-room-id` to be loaded before the javascript files, and then you won't need to refresh the page to start the stream 😄

**Comment by Goku-San** [comment]
Hello, @AndresGarciadelaHuerta 

Thanks for the answer, I solved all the problems, just forgot to write here and close the issue.

So for anyone else who stumbles upon this, the solution for **first problem** is as **AndresGarciadelaHuerta answered** and 
the **second is**  in ```RoomMessagesController``` **add** ```head :ok``` **before** ```RoomChannel.broadcast_to @room, @room_message``` :)
