### ISSUE TITLE
Error after removing coffee script gem

### ISSUE THREAD

**Issue by rpruizc** [iridakos/rails-chat-tutorial#5]
Right after the "Cleanup Unused Components", after restarting the server, I get an error that says: "cannot load such file -- coffee_script".
I checked my steps twice and restarted as many times as well. Bundle it again. Still the same error. Any ideas on what am I doing wrong?
Thank you for the article. Just what I am looking for to learn how to use websockets in rails.

**Comment by rpruizc** [comment]
Looks like the problem were two *.coffee files. Since we didn't use the --skip-coffee flag at project's creation, the coffee files are generated when the Room and RoomMessage resources are. Those files need to be removed/renamed (to *.js). A cache clear must also be performed (rails tmp:cache:clear).
That's what worked for me.

**Comment by iridakos** [comment]
You are right @rpruizc Thank you very much for pointing it out! Post updated.

https://iridakos.com/tutorials/2019/04/04/creating-chat-application-rails-websockets.html#acknowledgments
