### ISSUE TITLE
Rooms Index - already have authentication in place

### ISSUE THREAD

**Issue by tonydehnke** [iridakos/rails-chat-tutorial#6]
Hi, just working through your tutorial.  At the step in Rooms & Messages where you have us add the index.html.erb file.  That file does not load to display the h1 text as you had us add the before_action :authenticate_user! a few steps before - so it actually loads the Log In view.

**Comment by iridakos** [comment]
Hi @tonydehnke, thanks for pointing it out. Updated the post.

https://iridakos.com/tutorials/2019/04/04/creating-chat-application-rails-websockets.html#acknowledgments

**Comment by ampaire** [comment]
Login path is not working
