### ISSUE TITLE
Room index- app/views/rooms/index.html.erb  - missing row setup

### ISSUE THREAD

**Issue by tonydehnke** [iridakos/rails-chat-tutorial#7]
In the code window for:  "Open app/views/rooms/index.html.erb and change its contents to:"

Need to add the first line of:
<div class="row">

or it won't set up the two columns properly.   It's correct in the repo - https://github.com/iridakos/rails-chat-tutorial/blob/e1f2f225f885d2be8d579de3b16e989ad9709aa9/app/views/rooms/index.html.erb

So just need to update the code block in the tutorial.

![Untitled](https://user-images.githubusercontent.com/36720180/56054948-17658d00-5d0d-11e9-87de-401cd9ce3bba.png)

**Comment by iridakos** [comment]
@tonydehnke Thank you for reporting! Done, post updated.

https://iridakos.com/tutorials/2019/04/04/creating-chat-application-rails-websockets.html#acknowledgments
