### ISSUE TITLE
Missing Step - adding model room associations

### ISSUE THREAD

**Issue by tonydehnke** [iridakos/rails-chat-tutorial#8]
I couldn't get the messages window to load for me, kept getting an error of NoMethodError in RoomsController#show undefined method `room_messages’ for #<Room:0x00007f895b47ae78>

Reached out on the Ruby on Rails Link slack channel and Alfred Dominic pointed out that I was missing the association in the models.

Looked in the repo and it is there, so I think the step is missing in the tutorial to add this?

app/models/room.rb

 ```
class Room < ApplicationRecord		 
   has_many :room_messages, dependent: :destroy
 end
```

**Comment by iridakos** [comment]
@tonydehnke You are correct! Post updated.

Thank you very much for reporting.

https://iridakos.com/tutorials/2019/04/04/creating-chat-application-rails-websockets.html#acknowledgments
